gmail_username: 'suvankar.17@gmail.com'
gmail_password: '#*****!'
api_key: 'key-2ae5462343359b274501d6200d803c57'
domain: 'sandbox46f5651a3248462abc2acd3f1334cf39.mailgun.org'
username: 'postmaster@sandbox46f5651a3248462abc2acd3f1334cf39.mailgun.org'
password: 'b824f448c78923bfa2e5b86768d2c18f'
